# Generated by Django 4.1.4 on 2024-07-13 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accesslevel',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='useraccess',
            name='account',
        ),
        migrations.AlterField(
            model_name='accesslevel',
            name='name',
            field=models.CharField(choices=[('HO', 'Head Office'), ('DO', 'District Office'), ('BL', 'Branch Location')], max_length=2, unique=True),
        ),
    ]
