# Generated by Django 4.1.4 on 2024-07-13 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_accesslevel_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslevel',
            name='name',
            field=models.CharField(choices=[('HO', 'Head Office'), ('DO', 'District Office'), ('BL', 'Branch Location')], max_length=2),
        ),
    ]
